version: "3.8"

services:
  pedelogo-catalogo:
    depends_on: [mongodb]
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    environment:
      Mongo__Host: "mongodb"
      Mongo__User: "mongodb_user"
      Mongo__Password: "mongodb_pwd"
      Mongo__Port: "27017"
      Mongo__DataBase: "admin"
    networks:
      - pedelogo-network

  mongodb:
    image: mongo:4.2.8
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongodb_user
      MONGO_INITDB_ROOT_PASSWORD: mongodb_pwd
    networks:
      - pedelogo-network

networks:
  pedelogo-network:
